### ISSUE TITLE
Create payments page with all addresses transactions

### ISSUE THREAD

**Issue by chedieck** [PayButton/paybutton-server#180] opened 2022-07-21 15:16 UTC
Also the button/X page was unexpected -- but we can keep it.

We just want this info onto the payments page as well, all of the added button's txs togther. Only incoming payments as well, so outgoing txs would be filtered out.

_Originally posted by @Klakurka in https://github.com/PayButton/paybutton-server/issues/176#issuecomment-1190921365_

**Comment by Klakurka** [comment] 2022-07-21 15:26
Duplicate of https://github.com/PayButton/paybutton-server/issues/152

**Closed by Klakurka** 2022-07-21 15:26 UTC
